sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
# notifications:
  # email: false
before_script:
- npm install
script:
- npm run production

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master